name: github-actions-to-aws

on: push

jobs:
  run-container:
    name: run
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Configure CodeCommit Credential Helper
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true

      - name: Push to CodeCommit
        run: |
          git remote remove codecommit || true
          git remote add codecommit https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/pmwb_test_saito

          git fetch --unshallow || true

          git push -f codecommit HEAD:refs/heads/main
